YusukeIwaki/puppeteer-ruby

- lib/puppeteer/browser.rb
- lib/puppeteer/cdp_session.rb
- lib/puppeteer/connection.rb
- lib/puppeteer/dom_world.rb
- lib/puppeteer/execution_context.rb
- lib/puppeteer/frame_manager.rb
Workaround is no longer necessary after 345a4bf5b52b1397e4945bd0206b8da560391448.
> Remove workaround logics

- lib/puppeteer/dom_world.rb
- lib/puppeteer/frame.rb
- lib/puppeteer/page.rb
- lib/puppeteer/page/pdf_options.rb
* PrintToPDF is only available in headless mode (see: https://github.com/puppeteer/puppeteer/issues/1829 )
* `path` parameter is mandatry. If not specified, ArgumentError is raised because in most case user would forget to set it :)
> Implement Page#pdf

- lib/puppeteer/request.rb
```ruby
page.request_interception = true
page.on 'request' do |req|
headers = req.headers.merge(
foo: 'bar', # set "foo" header
origin: nil, # remove "origin" header
)
req.continue(headers: headers)
end
```
```ruby
page.request_interception = true
page.on 'request' do |req|
if req.url.include?("porn")
req.abort
else
req.continue
end
end
```
```ruby
page.request_interception = true
page.on 'request' do |req|
req.respond(
status: 404,
content_type: 'text/plain',
body: 'Not Found!'
)
end
```
> Implement request interception

- .circleci/config.yml
- lib/puppeteer/browser.rb
- spec/integration/browser_spec.rb
- spec/integration/page_spec.rb
- spec/spec_helper.rb
Original puppeteer has many unit tests with running Puppeteer.
https://github.com/puppeteer/puppeteer/blob/main/test/browser.spec.ts
Let's use it also in puppeteer-ruby!
> Introduce integration spec (run with Puppeteer)

- .circleci/config.yml
> change RSpec output format in CircleCI

- lib/puppeteer.rb
- lib/puppeteer/browser.rb
- lib/puppeteer/browser_context.rb
- lib/puppeteer/connection.rb
- lib/puppeteer/page.rb
- lib/puppeteer/web_socket.rb
- spec/integration/browser_context_spec.rb
- spec/integration/browser_spec.rb
* https://github.com/puppeteer/puppeteer/blob/v5.2.1/test/browser.spec.ts
* https://github.com/puppeteer/puppeteer/blob/v5.2.1/test/browsercontext.spec.ts
> add RSpec: Browser, BrowserContext

- lib/puppeteer/element_handle.rb
- lib/puppeteer/keyboard.rb
- spec/integration/click_spec.rb
- spec/integration/keyboard_spec.rb
- spec/spec_helper.rb
- spec/utils.rb
* https://github.com/puppeteer/puppeteer/blob/v5.2.1/test/keyboard.spec.ts
> add RSpec: keyboard

- lib/puppeteer/dom_world.rb
- lib/puppeteer/frame.rb
- lib/puppeteer/page.rb
- lib/puppeteer/wait_task.rb
- spec/integration/wait_task_spec.rb
https://github.com/puppeteer/puppeteer/blob/v5.2.1/test/waittask.spec.ts
> add RSpec: WaitTask

- lib/puppeteer/js_handle.rb
- lib/puppeteer/remote_object.rb
- spec/integration/js_handle_spec.rb
* https://github.com/puppeteer/puppeteer/blob/main/test/jshandle.spec.ts
> add RSpec: JSHandle

- spec/integration/query_selector_spec.rb
https://github.com/puppeteer/puppeteer/blob/v5.2.1/test/queryselector.spec.ts
> add RSpec: query_selector_spec

- lib/puppeteer/cdp_session.rb
- lib/puppeteer/connection.rb
- spec/integration/cdp_session_spec.rb
https://github.com/puppeteer/puppeteer/blob/v5.3.0/test/CDPSession.spec.ts
> add RSpec: CDPSession_spec

- lib/puppeteer/frame.rb
- spec/integration/frame_spec.rb
- spec/utils.rb
https://github.com/puppeteer/puppeteer/blob/b1c3efaa34af49fb3d7a1ccabb1283600fbd3920/test/frame.spec.ts
including https://github.com/puppeteer/puppeteer/pull/6416, https://github.com/puppeteer/puppeteer/pull/6398
> add RSpec: frame_spec

- spec/integration/keyboard_spec.rb
> add RSpec for inputing '('

- lib/puppeteer.rb
- lib/puppeteer/browser_runner.rb
- lib/puppeteer/concurrent_ruby_utils.rb
- lib/puppeteer/launcher.rb
- lib/puppeteer/launcher/browser_options.rb
- lib/puppeteer/launcher/chrome.rb
- lib/puppeteer/launcher/firefox.rb
- lib/puppeteer/page.rb
- spec/integration/launcher_spec.rb
- spec/puppeteer/launcher/chrome_arg_options_spec.rb
- spec/spec_helper.rb
https://github.com/puppeteer/puppeteer/blob/main/test/launcher.spec.ts
> add RSpec: launcher spec

- lib/puppeteer/page.rb
- lib/puppeteer/page/cookie_data.rb
- spec/integration/cookies_spec.rb
> add Cookies feature

- lib/puppeteer/launcher/chrome.rb
- spec/integration/launcher_spec.rb
- spec/spec_helper.rb
> Prevent creating a blank page on Puppeteer.launch(headless: false)

- lib/puppeteer/dom_world.rb
- lib/puppeteer/frame.rb
- lib/puppeteer/page.rb
- spec/integration/page_spec.rb
> Implement Page#add_script_tag

- lib/puppeteer/dom_world.rb
- spec/integration/page_spec.rb
> Implement Page#add_style_tag

- spec/integration/page_spec.rb
> Add RSpec for Page#bypass_csp=

- .github/workflows/windows_check.yml
- lib/puppeteer/browser_runner.rb
- lib/puppeteer/env.rb
- lib/puppeteer/launcher/base.rb
- lib/puppeteer/web_socket.rb
- lib/puppeteer/web_socket_transport.rb
- spec/integration/example_spec.rb
> Make puppeteer-ruby windows compatible

- README.md
Hi, Yusuke-san,
This is my first time using a puppeteer.  I found this repository useful and helpful. 
As a very newbie, when I just copied the sample codes in README.md to a new file to run, it showed an error that it could not find the module. As a result, I add the `require` statement in the sample codes. Even though this is a tiny change, I think it would be more friendly for new coming users to get started.
> Add 'require' statement to sample code

- .github/workflows/check.yml
- README.md
- development/generate_api_coverage.rb
- docs/api_coverage.md
- lib/puppeteer.rb
- lib/puppeteer/env.rb
- lib/puppeteer/page.rb
- lib/puppeteer/puppeteer.rb
- lib/puppeteer/version.rb
- puppeteer-ruby.gemspec
resolves #71 
Now we can see which methods are available on puppeteer-ruby easily :)
> Generate api coverages

- lib/puppeteer/page.rb
> fix Page.pdf on Windows

- CHANGELOG.md
- lib/puppeteer/wait_task.rb
- spec/integration/wait_task_spec.rb
> [hotfix] Fix wait_for_selector to work

- lib/puppeteer/page.rb
- lib/puppeteer/page/pdf_options.rb
- spec/integration/example_spec.rb
* resolves #77 
* include https://github.com/puppeteer/puppeteer/pull/6981
> fix PDF options to work

- lib/puppeteer/element_handle.rb
- spec/integration/input_spec.rb
> fix ElementHandle#set_input_files to work

- lib/puppeteer/element_handle.rb
- spec/integration/input_spec.rb
> add spec for FileChooser

- lib/puppeteer/browser.rb
- puppeteer-ruby.gemspec
- spec/spec_helper.rb
> Workaround for Target.createTarget

- lib/puppeteer/web_socket.rb
resolves #94 
```
ws_url = "wss://chrome.browserless.io?token=#{ENV['BROWSERLESS_IO_API_TOKEN']}"
Puppeteer.connect(browser_ws_endpoint: ws_url) do |browser|
page = browser.new_page
page.goto('chrome://gpu/')
page.screenshot(path: './gpu.png', full_page: true)
end
```
> Enable connect to "wss://..." endpoint directly (ex. browserless.io)

- docs/api_coverage.md
- lib/puppeteer/emulation_manager.rb
- lib/puppeteer/page.rb
- lib/puppeteer/puppeteer.rb
- spec/integration/emulation_spec.rb
> add Emulation specs

- lib/puppeteer/page.rb
- lib/puppeteer/page/pdf_options.rb
- lib/puppeteer/protocol_stream_reader.rb
- lib/puppeteer/tracing.rb
- spec/integration/example_spec.rb
- spec/integration/page_spec.rb
fixes #125 
https://github.com/puppeteer/puppeteer/pull/5731 is ported into puppeteer-ruby
> Allow Page#pdf to work without path parameter

- .circleci/config.yml
- spec/integration/emulation_spec.rb
https://circleci.com/developer/images/image/cimg/ruby
> Use cimg insteadof legacy circleci images

- .github/workflows/rspec_alpine.yml
- README.md
- spec/integration/launcher_spec.rb
- spec/spec_helper.rb
> Add CI with ruby:alpine

- docs/api_coverage.md
- lib/puppeteer.rb
- lib/puppeteer/devices.rb
- lib/puppeteer/network_condition.rb
- lib/puppeteer/network_conditions.rb
- lib/puppeteer/network_manager.rb
- lib/puppeteer/page.rb
- lib/puppeteer/puppeteer.rb
- spec/integration/emulation_spec.rb
Include https://github.com/puppeteer/puppeteer/pull/6759
> add Page#emulateNetworkConditions

- docs/api_coverage.md
- lib/puppeteer/page.rb
- spec/integration/page_spec.rb
```ruby
page.expose_function('compute', -> (x, y) { x + y })
page.evaluate('async () => { return await globalThis.compute(3, 4) }') # => 7
```
> Implement Page#expose_function

- lib/puppeteer/browser_context.rb
- spec/integration/page_spec.rb
Include https://github.com/puppeteer/puppeteer/pull/5295
refs #143
> Add durableStorage to allowed permissions

- lib/puppeteer/devices.rb
Include https://github.com/puppeteer/puppeteer/pull/7210
refs #143
> Add more Android models to DeviceDescriptors

- lib/puppeteer/tracing.rb
- spec/integration/tracing_spec.rb
Include https://github.com/puppeteer/puppeteer/pull/7413
refs #143
> use non-deprecated tracing categories api

- lib/puppeteer/coverage.rb
- lib/puppeteer/js_coverage.rb
- spec/integration/coverage_spec.rb
Include https://github.com/puppeteer/puppeteer/pull/6454
refs #143
> option for raw V8 script coverage

- lib/puppeteer/web_socket.rb
Include https://github.com/puppeteer/puppeteer/pull/5614
refs #143
> Add User-Agent with Puppeteer version to WebSocket request

- docs/api_coverage.md
- lib/puppeteer/http_request.rb
- lib/puppeteer/network_manager.rb
- lib/puppeteer/page.rb
- spec/integration/request_interception_spec.rb
resolves #155 
refs https://github.com/puppeteer/puppeteer/pull/6735
> Implement cooperative request interception

- lib/puppeteer/page.rb
- lib/puppeteer/wait_task.rb
- spec/integration/example_spec.rb
- spec/integration/page_spec.rb
fixes #164 
0 is falsey in JavaScript, but it is truthy in Ruby.
> Allow "timeout: 0" for disabling timeout.

- .gitignore
- lib/puppeteer/element_handle.rb
- spec/integration/screenshot_spec.rb
- fixes bug in ElementHandle#screenshot
- enables ElementHandle#screenshot specs
> ElementHandle#screenshot

- lib/puppeteer/page/screenshot_options.rb
https://github.com/puppeteer/puppeteer/pull/7631
refs #170
> fix: add webp to screenshot quality option allow list

- lib/puppeteer/launcher/chrome.rb
- lib/puppeteer/launcher/firefox.rb
- spec/integration/launcher_spec.rb
https://github.com/puppeteer/puppeteer/pull/7596
refs #170
> fix(launcher): launcher.launch() should pass 'timeout' option

- lib/puppeteer/aria_query_handler.rb
- spec/integration/aria_query_handler_spec.rb
ref https://github.com/puppeteer/puppeteer/pull/7750
refs  #170
> fix(ariaqueryhandler): allow single quotes in aria attribute selector

- lib/puppeteer/frame_manager.rb
from: https://github.com/puppeteer/puppeteer/pull/7773
refs: #170
> fix: null check for frame in FrameManager

- lib/puppeteer/launcher/chrome.rb
- lib/puppeteer/launcher/firefox.rb
from https://github.com/puppeteer/puppeteer/pull/7762
refs #170
> fix: only kill the browser process when it cannot be started but not when waiting on the first target

- .circleci/config.yml
- lib/puppeteer/browser_runner.rb
- lib/puppeteer/launcher/chrome.rb
- lib/puppeteer/launcher/firefox.rb
- lib/puppeteer/launcher/launch_options.rb
- spec/integration/launcher_spec.rb
from https://github.com/puppeteer/puppeteer/pull/7684, https://github.com/puppeteer/puppeteer/pull/7761
closes #170 🍰
> Correctly prepare Firefox profiles with required preferences

- lib/puppeteer/devices.rb
from https://github.com/puppeteer/puppeteer/pull/7904
> feat: add more models to DeviceDescriptors

- docs/api_coverage.md
- lib/puppeteer/console_message.rb
- lib/puppeteer/page.rb
- spec/integration/page_spec.rb
ref: https://github.com/puppeteer/puppeteer/commit/96f3d439f5748ff707d64fb41af50786c0d33ad7
resolves #199
> Fix consoleMessage API

- development/generate_api_coverage.rb
- docs/api_coverage.md
- lib/puppeteer/http_request.rb
- spec/integration/request_interception_spec.rb
memo:
https://github.com/puppeteer/puppeteer/blame/3b886364dd38dbb17a543cf1af3876ba9b3e5f2e/src/common/HTTPRequest.ts#L268
https://github.com/puppeteer/puppeteer/commit/dc23b7535cb958c00d1eecfe85b4ee26e52e2e39
https://github.com/puppeteer/puppeteer/pull/7796/files
https://github.com/puppeteer/puppeteer/commit/824242246de9e158aacb85f71350a79cb386ed92
> fix request interception

- lib/puppeteer/page.rb
- spec/integration/cookies_spec.rb
> Add a parameter assertion for Page#set_cookie and Page#delete_cookie

- lib/puppeteer/browser_runner.rb
include https://github.com/puppeteer/puppeteer/pull/8233
> fix: also kill Firefox when temporary profile is used

- lib/puppeteer/launcher/chrome.rb
include https://github.com/puppeteer/puppeteer/pull/8196
> fix: disable bfcache in the launcher

- lib/puppeteer/network_event_manager.rb
- lib/puppeteer/network_manager.rb
include https://github.com/puppeteer/puppeteer/pull/8239
> fix: forget queuedEventGroup when emitting response in responseReceivedExtraInfo

- lib/puppeteer/browser.rb
- lib/puppeteer/browser_context.rb
- lib/puppeteer/target.rb
Porting https://github.com/puppeteer/puppeteer/pull/8460
> fix: use isPageTargetCallback in Browser::pages()

- lib/puppeteer/element_handle.rb
- spec/integration/input_spec.rb
Porting https://github.com/puppeteer/puppeteer/pull/8472
> fix: don't throw on bad access

- spec/assets/csscoverage/empty.html
- spec/integration/coverage_spec.rb
https://github.com/puppeteer/puppeteer/pull/8570
Only rspec is added.
> fix: CSS coverage should work with empty stylesheets

- lib/puppeteer/frame.rb
- spec/integration/frame_spec.rb
https://github.com/puppeteer/puppeteer/pull/8657
> feat: expose the page getter on Frame

- lib/puppeteer/launcher/chrome.rb
Porting https://github.com/puppeteer/puppeteer/pull/8706
> fix: disable AcceptCHFrame

- lib/puppeteer/frame_manager.rb
- lib/puppeteer/lifecycle_watcher.rb
Porting https://github.com/puppeteer/puppeteer/pull/8717
> fix: use loaderId to reduce test flakiness

- lib/puppeteer/query_handler_manager.rb
- spec/integration/query_handler_spec.rb
Porting https://github.com/puppeteer/puppeteer/pull/8956 without JS injection codes
> feat: add text query handler

- lib/puppeteer/launcher/firefox.rb
> Add prefs to make CDP with firefox work

- lib/puppeteer/browser_context.rb
- spec/integration/browser_context_spec.rb
Porting https://github.com/puppeteer/puppeteer/pull/9134
> feat: expose browser context id

- lib/puppeteer/coverage.rb
- lib/puppeteer/js_coverage.rb
- spec/assets/jscoverage/ranges.html
- spec/integration/coverage_spec.rb
Porting https://github.com/puppeteer/puppeteer/pull/9027
> feat: add ability to collect JS code coverage at the function level

- lib/puppeteer/lifecycle_watcher.rb
porting https://github.com/puppeteer/puppeteer/pull/9178
> fix: resolve navigation requests when request fails

- lib/puppeteer/element_handle.rb
- spec/integration/element_handle_spec.rb
Porting https://github.com/puppeteer/puppeteer/pull/9352
> feat: add element validation

- .github/workflows/deploy.yml
- lib/puppeteer/launcher/chrome.rb
- lib/puppeteer/version.rb
> introduce PUPPETEER_RUBY_NO_SANDBOX

- lib/puppeteer/chrome_target_manager.rb
> fix hang on site using ServiceWorker
