.circleci/config.yml
.github/workflows/reviewdog.yml
lib/puppeteer/browser.rb
lib/puppeteer/frame_manager.rb
puppeteer-ruby.gemspec

also, Style/AndOr is updated after rubocop 0.83.
https://github.com/rubocop-hq/rubocop/pull/7959
Revert the proper usage of or.

Execute Rubocop with GitHub Actions

---

lib/puppeteer.rb
lib/puppeteer/async_await_behavior.rb
lib/puppeteer/browser.rb
lib/puppeteer/cdp_session.rb
lib/puppeteer/connection.rb
lib/puppeteer/define_async_method.rb
lib/puppeteer/dom_world.rb
lib/puppeteer/element_handle.rb
lib/puppeteer/emulation_manager.rb
lib/puppeteer/execution_context.rb
lib/puppeteer/frame.rb
lib/puppeteer/frame_manager.rb
lib/puppeteer/js_handle.rb
lib/puppeteer/keyboard.rb
lib/puppeteer/mouse.rb
lib/puppeteer/page.rb
lib/puppeteer/remote_object.rb
lib/puppeteer/touch_screen.rb
lib/puppeteer/wait_task.rb
spec/puppeteer/async_await_behavior_spec.rb
spec/puppeteer/concurrent_ruby_utils_spec.rb
spec/puppeteer/define_async_method_spec.rb

`async def ...` are boilerplate codes. Replace it with `define_async_method`
```
def click
...
end
async def async_click
click
end
```
```
def click
...
end
define_async_method :async_click
```

replace async def ... with define_async_method

---

.rubocop.yml
puppeteer-ruby.gemspec

RuboCop 0.89 introduces many useful cops
https://github.com/rubocop-hq/rubocop/releases/tag/v0.89.0
I want to use 
* Style/ExplicitBlockArgument
* Style/StringConcatenation
and so on...

bump rubocop to 0.89

---

lib/puppeteer/page.rb
spec/integration/keyboard_spec.rb

REMARK: This feature is NOT originated from JS version of puppeteer. Available only in puppeteer-ruby.
It would be better if we can describe sequential operations with keyboard block like below:
```ruby
page.click('input')
page.keyboard {
type_text '123456789'
down 'Shift'
5.times { press 'ArrowLeft' }
up 'Shift'
send_character 'a'
}
```
rather than
```ruby
page.click('input')
page.keyboard.type_text '123456789'
page.keyboard.down 'Shift'
5.times { page.keyboard.press 'ArrowLeft' }
page.keyboard.up 'Shift'
page.keyboard.send_character 'a'
```

add feature: keyboard with block

---

.github/workflows/reviewdog.yml
.rubocop.yml
lib/puppeteer.rb
lib/puppeteer/debug_print.rb
lib/puppeteer/define_async_method.rb
puppeteer-ruby.gemspec

* Introduced some usefule Cops, such as EmptyLineAfterMultilineCondition, ClassMethodsDefinitions, RedundantSelfAssignment
* Removed Lint/MissingSuper, because it is often bring false-positive comments.

Bump rubocop 0.90

---

.circleci/config.yml
Dockerfile
docker-compose.yml
lib/puppeteer/browser_runner.rb
lib/puppeteer/element_handle.rb
lib/puppeteer/env.rb
lib/puppeteer/launcher.rb
lib/puppeteer/launcher/base.rb
lib/puppeteer/launcher/chrome.rb
lib/puppeteer/launcher/firefox.rb
lib/puppeteer/remote_object.rb
spec/integration/browser_context_spec.rb
spec/integration/browser_spec.rb
spec/integration/click_spec.rb
spec/integration/element_handle_spec.rb
spec/integration/js_handle_spec.rb
spec/integration/keyboard_spec.rb
spec/spec_helper.rb

Now we can enjoy automation with Firefox, by specifying `product: firefox`
```ruby
Puppeteer.launch(headless: false, product: 'firefox') do |browser|
page = browser.pages.first || browser.new_page
page.goto('https://www.google.com/')
page.click("input[name='q']")
page.keyboard {
type_text 'puppeteer'
press 'Enter'
}
sleep 10
end
```

add Firefox support

---

lib/puppeteer/concurrent_ruby_utils.rb
spec/puppeteer/concurrent_ruby_utils_spec.rb

When we use future like `future { hoge }` , it doesn't raise error and nothing is shown in log.
It is hard to detect some mistakes (such as typo).
```
W, [2020-11-14T03:30:27.918673 #12501]  WARN -- : undefined local variable or method `undefined_variable_is_me' for #<RSpec::ExampleGroups::PuppeteerConcurrentRubyUtils::Future:0x00007fe2534a7350> (NameError)
/Users/yusuke-iwaki/src/github.com/YusukeIwaki/puppeteer-ruby/vendor/bundle/ruby/2.6.0/gems/rspec-expectations-3.9.0/lib/rspec/matchers.rb:963:in `method_missing'
```
With this PR, error will be shown in STDERR as a warning.

show warning in "#future"

---

.rubocop.yml
lib/puppeteer.rb
lib/puppeteer/browser.rb
lib/puppeteer/browser_context.rb
lib/puppeteer/cdp_session.rb
lib/puppeteer/connection.rb
lib/puppeteer/dom_world.rb
lib/puppeteer/event_callbackable.rb
lib/puppeteer/events.rb
lib/puppeteer/frame_manager.rb
lib/puppeteer/lifecycle_watcher.rb
lib/puppeteer/network_manager.rb
lib/puppeteer/page.rb
lib/puppeteer/target.rb
spec/integration/browser_context_spec.rb
spec/integration/click_spec.rb
spec/integration/keyboard_spec.rb
spec/integration/wait_task_spec.rb
spec/puppeteer/event_callbackable_spec.rb
spec/spec_helper.rb

The logic of `Page#on` in puppeteer-ruby was far different from original (JS) implementation.
This PR introduces Events constants and makes the method similar to the original implementation.
Also, introduces XXXEmittedEvents, which is already introduces in puppeteer JS https://github.com/puppeteer/puppeteer/pull/6179 or https://github.com/puppeteer/puppeteer/pull/6174

Refactor event

---

lib/puppeteer/cdp_session.rb

After https://github.com/YusukeIwaki/puppeteer-ruby/commit/345a4bf5b52b1397e4945bd0206b8da560391448, workaround logic seemed to be no longer required.
However, the unordered RECV/SEND occasionally happens...
```
D, [2020-11-27T18:57:37.153280 #21053] DEBUG -- : RECV << {"id"=>3, "result"=>{}, "sessionId"=>"3B6890FD90EFCE617B47AE0AA959FBF0"}
W, [2020-11-27T18:57:37.153463 #21053]  WARN -- : undefined local variable or method `id' for #<Puppeteer::CDPSession:0x00007fcc37d14a10> (NameError)
/Users/yusuke-iwaki/src/github.com/YusukeIwaki/puppeteer-ruby/lib/puppeteer/cdp_session.rb:47:in `handle_message'
/Users/yusuke-iwaki/src/github.com/YusukeIwaki/puppeteer-ruby/lib/puppeteer/connection.rb:199:in `handle_message'
/Users/yusuke-iwaki/src/github.com/YusukeIwaki/puppeteer-ruby/lib/puppeteer/def …
```

Revert deletion of workaround for unordered SEND/RECV 

---

lib/puppeteer/browser_runner.rb
lib/puppeteer/cdp_session.rb
lib/puppeteer/connection.rb
spec/puppeteer/cdp_session_spec.rb

Reverts YusukeIwaki/puppeteer-ruby#32
raw_send was
```
payload = JSON.fast_generate(message.compact.merge(id: id))
@transport.send_text(payload)
request_debug_printer.handle_payload(payload)
id
```
```
id = @connection.raw_send(message: { sessionId: @session_id, method: method, params: params })
@callbacks[id] = MessageCallback.new(method: method, promise: promise)
```
With this implementation, we cannot handle message before raw_send returns the id.
If handle_message is called soon after send_text, it causes `unknown id` error, because the caller doesn't know the generated id.
So I changed this implementation. id is generated in advance, and raw_send just send text with given id.
```
@connection.generate_id do |id|
@callbacks[id] = Puppeteer::Connection::MessageCallback.new(method: …
```

Revert "Revert deletion of workaround for unordered SEND/RECV "

---

lib/puppeteer/concurrent_ruby_utils.rb

Timeout error logs are really annoying. It doesn't imply anything. So suppress it.
| before | after |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/11763113/102839305-892f2d00-4443-11eb-86fc-746e0484b749.png)|  ![image](https://user-images.githubusercontent.com/11763113/102839371-b67bdb00-4443-11eb-8e57-77a8cf3b2e7d.png) |

Suppress Puppeteer::TimeoutError logging

---

spec/integration/page_spec.rb

CI often fails the error below:
```
Failures:
1) Puppeteer::Page#cache_enabled should stay disabled when toggling request interception on/off
Failure/Error: expect(response_count).to eq(2)
expected: 2
got: 3
(compared using ==)
```
It is caused by `Time.now` timing.

Increace CI stability

---

lib/puppeteer/launcher/chrome.rb
lib/puppeteer/page.rb
spec/integration/idle_override_spec.rb

resolves #38 
`Page#emulateIdleState` https://github.com/puppeteer/puppeteer/pull/6410

implement Page#emulate_idle_state

---

lib/puppeteer/launcher/chrome.rb
spec/integration/launcher_spec.rb
spec/spec_helper.rb

Reverts YusukeIwaki/puppeteer-ruby#48, refs #47
It seems we can't use Capybara with `--no-startup-window`...

Revert "Prevent creating a blank page on Puppeteer.launch(headless: false)"

---

.circleci/config.yml
spec/integration/page_spec.rb

`target=_blank` assumes rel=noopener by default in Chrome >= 88
https://www.chromestatus.com/feature/6140064063029248

Fix window.opener spec with target=_blank

---

lib/puppeteer/page.rb
spec/integration/evaluation_spec.rb

ref: https://github.com/rubycdp/ferrum/issues/132
Some users use `evaluateOnNewDocument`

Implement Page#evaluate_on_new_document

---

lib/puppeteer/connection.rb

CI shows that create_cdp_session is flaky.
https://app.circleci.com/pipelines/github/YusukeIwaki/puppeteer-ruby/468/workflows/44619157-feeb-46fc-a64c-44ba94a2eb98/jobs/1035
We expect the response of `Target.attachToTarget` is notified after `Target.attachedToTarget` as below.
```
D, [2021-03-24T02:31:58.468327 #185] DEBUG -- : SEND >> {"method":"Target.attachToTarget","params":{"targetId":"55C49F240E82162425206714EEF541C0","flatten":true},"id":3}
D, [2021-03-24T02:31:58.472950 #185] DEBUG -- : RECV << {"method"=>"Target.targetInfoChanged", "params"=>{"targetInfo"=>{"targetId"=>"55C49F240E82162425206714EEF541C0", "type"=>"page", "title"=>"about:blank", "url"=>"about:blank", "attached"=>true, "canAccessOpener"=>false, "browserContextId"=>"8A2A380840AA61C4436771D626A7D501"}}}
D, …
```

Revert "Remove ugly logic in Connection"

---

lib/puppeteer/connection.rb
spec/integration/page_spec.rb

Handle message sync if needed for avoiding flaky test failure

---

lib/puppeteer/emulation_manager.rb
spec/integration/screenshot_spec.rb

resolves #96 
current version:
```
Failures:
1) Screenshots full_page with Mobile viewport behaves like keep input value is expected to eq "my value"
Failure/Error: expect(page.eval_on_selector('textarea', 'input => input.value')).to eq('my value')
expected: "my value"
got: ""
(compared using ==)
Shared Example Group: "keep input value" called from ./spec/integration/screenshot_spec.rb:153
2) Screenshots full_page with 1200x1200 viewport behaves like keep input value is expected to eq "my value"
Failure/Error: expect(page.eval_on_selector('textarea', 'input => input.value')).to eq('my value')
expected: "my value"
got: ""
(compared using ==)
Shared Example Group: "keep input value" called from ./spec/integration/screenshot_spec.rb:161
Finished in 6.74 seconds (files took 0.90863 seconds to …
```

Fix full page screenshot

---

lib/puppeteer/browser_runner.rb

Another implementation for #105 
```
EOFError:
end of file reached
```
```
Puppeteer::BrowserRunner::LaunchError:
Failed to launch browser! 
[19476:19476:0518/105840.008914:ERROR:browser_main_loop.cc(1473)] Unable to open X display.
[0518/105840.067136:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
```

raise LaunchError when Chrome crashed on launch.

---

lib/puppeteer/events.rb

resolves #111 
```
$ bundle exec rails c
Running via Spring preloader in process 48701
Loading development environment (Rails 6.1.3.2)
irb(main):001:0> require 'puppeteer'
Traceback (most recent call last):
1: from (irb):1
NoMethodError (undefined method `Symbol' for main:Object)
```
```
[3] pry(main)> require 'puppeteer'
=> true
[4] pry(main)> ConnectionEmittedEvents
=> ConnectionEmittedEvents
[5] pry(main)> ConnectionEmittedEvents::Disconnected
=> "029e1174b931fe23bb558f0852cdc3af"
```

fix require error on Rails.

---

puppeteer-ruby.gemspec

refs #118 
This gem is not tested on Ruby 2.3, 2.4, 2.5, and actually not working on them. https://github.com/YusukeIwaki/puppeteer-ruby/pull/120
We should specify required Ruby version.

Specify required Ruby version

---

lib/puppeteer/page/pdf_options.rb
spec/puppeteer/page/pdf_options_spec.rb

fixes #119 
spec failed before fix:
```
Failures:
1) Puppeteer::Page::PDFOptions convert_print_parameter_to_inches value is number is expected to eq 0.10416666666666667
Failure/Error: it { is_expected.to eq(10 / 96.0) }
expected: 0.10416666666666667
got: 0
(compared using ==)
2) Puppeteer::Page::PDFOptions convert_print_parameter_to_inches value is decimal is expected to eq 0.109375
Failure/Error: it { is_expected.to eq(10.5 / 96.0) }
expected: 0.109375
got: 0
(compared using ==)
3) Puppeteer::Page::PDFOptions convert_print_parameter_to_inches value is number without unit is expected to eq 0.10416666666666667
Failure/Error: it { is_expected.to eq(10 / 96.0) }
expected: 0.10416666666666667
got: 0
(compared using ==)
4) Puppeteer::Page::PDFOptions convert_print_parameter_to_inches value is …
```

Fix calculation logic for PDF options

---

README.md
docs/api_coverage.md
lib/puppeteer/concurrent_ruby_utils.rb
lib/puppeteer/define_async_method.rb
lib/puppeteer/frame.rb
lib/puppeteer/page.rb
spec/integration/browser_context_spec.rb
spec/integration/click_spec.rb
spec/integration/example_spec.rb
spec/integration/frame_spec.rb
spec/integration/input_spec.rb
spec/integration/launcher_spec.rb
spec/integration/page_spec.rb
spec/integration/wait_task_spec.rb
spec/puppeteer/concurrent_ruby_utils_spec.rb
spec/puppeteer/define_async_method_spec.rb

resolves #123 
Async API:
```ruby
await_all(
page.async_wait_for_navigation,
page.async_click('#submit'),
)
```
Sync API with block:
```ruby
page.wait_for_navigation do
page.click('#submit')
end
```
Async API is familiar to JavaScript users, however Ruby users would like to use Sync API.

Define sync API with block

---

lib/puppeteer/concurrent_ruby_utils.rb
lib/puppeteer/define_async_method.rb
spec/integration/launcher_spec.rb

The block call of wait_for_xxx should be evaluated after wait_for_xxx. However Concurrent::Promises.zip(promises) don't ensure the order of evaluation of promises.
```ruby
js = <<~JAVASCRIPT
() => {
const el = document.createElement('input');
el.type = 'file';
el.click();
}
JAVASCRIPT
chooser = page.wait_for_file_chooser do
page.evaluate(js)
end
```
This spec often failed:
```
D, [2021-08-14T12:54:05.059535 #1144] DEBUG -- : SEND >> {"sessionId":"F60931875D40811439D39D5418D08D05","method":"Runtime.callFunctionOn","params":{"functionDeclaration":"() => {\n  const el = document.createElement('input');\n  el.type = 'file';\n  el.click();\n}\n\n//# sourceURL=__puppeteer_evaluation_script__\n","executionContextId":1,"arguments":[],"returnByValue":true,"awaitPromise":true,"userGesture":true},"id …
```

Improve define_async_method.

---

docs/api_coverage.md
lib/puppeteer/page.rb
spec/integration/emulation_spec.rb

Include https://github.com/puppeteer/puppeteer/pull/7343

Implement Page#emulate_cpu_throttling

---

lib/puppeteer.rb

Currently, `Puppeteer.public_methods` doesn't show `launch` or `connect`. method_missing can be replaced with define_method here.

Replace method_missing with define_method

---

lib/puppeteer/page.rb
lib/puppeteer/page/screenshot_options.rb
spec/integration/screenshot_spec.rb

Include https://github.com/puppeteer/puppeteer/pull/7565
refs #143

Add webp to screenshot options

---

docs/api_coverage.md
lib/puppeteer/http_request.rb
spec/assets/initiator.html
spec/assets/initiator.js
spec/integration/network_spec.rb

ref: https://github.com/puppeteer/puppeteer/pull/7614
refs #170

feat: add initiator to HTTPRequest

---

.circleci/config.yml
docs/api_coverage.md
lib/puppeteer/cdp_session.rb
lib/puppeteer/dom_world.rb
lib/puppeteer/frame.rb
lib/puppeteer/frame_manager.rb
lib/puppeteer/page.rb
lib/puppeteer/target.rb
spec/assets/dynamic-oopif.html
spec/assets/oopif.html
spec/integration/frame_spec.rb
spec/integration/launcher_spec.rb
spec/integration/oopif_spec.rb
spec/integration/page_spec.rb
spec/integration/wait_task_spec.rb
spec/spec_helper.rb

ref: https://github.com/puppeteer/puppeteer/pull/7556
refs #170

Support OOP iframe

---

lib/puppeteer/network_manager.rb

from: https://github.com/puppeteer/puppeteer/issues/7802
refs #184

handle multiple/duplicate Fetch.requestPaused events

---

lib/puppeteer/aria_query_handler.rb
lib/puppeteer/custom_query_handler.rb
lib/puppeteer/dom_world.rb
lib/puppeteer/element_handle.rb
lib/puppeteer/js_handle.rb
lib/puppeteer/query_handler_manager.rb
lib/puppeteer/wait_task.rb
spec/integration/aria_query_handler_spec.rb
spec/integration/element_handle_spec.rb

refs #184 
from: https://github.com/puppeteer/puppeteer/pull/7825, https://github.com/puppeteer/puppeteer/pull/7843

feat: implement Element.waitForSelector

---

lib/puppeteer/network_event_manager.rb

This previously caused a crash when applying a response listener.

Fix: spelling of forget_request_paused method

---

lib/puppeteer/browser_runner.rb

resolves #194 
```
From: /Users/yusuke-iwaki/src/github.com/YusukeIwaki/puppeteer-ruby/bin/console:14 :
9: # (If you use this, don't forget to add pry to your Gemfile!)
10: require 'pry'
11: Puppeteer.launch(channel: 'chrome', handle_SIGINT: false) do |browser|
12:   page = browser.new_page
13:   binding.pry
=> 14: end
[1] pry(main)> 
[1] pry(main)> page.goto('https://github.com/YusukeIwaki')
W, [2022-02-01T23:27:51.584141 #61772]  WARN -- : Protocol error (Page.navigate): Session closed. Most likely the page has been closed. (Puppeteer::CDPSession::Error)
/Users/yusuke-iwaki/src/github.com/YusukeIwaki/puppeteer-ruby/lib/puppeteer/cdp_session.rb:37:in `async_send_message'
/Users/yusuke-iwaki/src/github.com/YusukeIwaki/puppeteer-ruby/lib/puppeteer/cdp_session.rb:29:in `send_message' …
```

Prevent SIGINT to be passed into Chrome

---

lib/puppeteer/element_handle.rb
lib/puppeteer/element_handle/box_model.rb
lib/puppeteer/frame_manager.rb
lib/puppeteer/js_handle.rb
lib/puppeteer/page.rb
spec/integration/oopif_spec.rb
spec/puppeteer/element_handle_spec.rb

Implement [13.1.0](https://github.com/puppeteer/puppeteer/releases/tag/v13.1.0) features. 2 PRs below:
* https://github.com/puppeteer/puppeteer/pull/7900
* https://github.com/puppeteer/puppeteer/pull/7906
* https://github.com/puppeteer/puppeteer/pull/7911

fix: correctly compute clickable points for elements inside OOPIFs

---

lib/puppeteer/events.rb
lib/puppeteer/frame_manager.rb
lib/puppeteer/lifecycle_watcher.rb
lib/puppeteer/page.rb
spec/integration/oopif_spec.rb

https://github.com/puppeteer/puppeteer/pull/8117

fix: waitForNavigation in OOPIFs

---

lib/puppeteer/network_manager.rb
spec/integration/request_interception_spec.rb

port https://github.com/puppeteer/puppeteer/pull/8162

fix: get extra headers from Fetch.requestPaused event

---

lib/puppeteer/http_request.rb
spec/integration/request_interception_spec.rb

Include https://github.com/puppeteer/puppeteer/pull/8183

feat: respond multiple headers with same key

---

lib/puppeteer/execution_context.rb
lib/puppeteer/frame_manager.rb
lib/puppeteer/page.rb
spec/assets/inner-frame1.html
spec/assets/inner-frame2.html
spec/assets/main-frame.html
spec/integration/oopif_spec.rb
spec/spec_helper.rb

porting https://github.com/puppeteer/puppeteer/pull/8304

fix: make sure inner OOPIFs can be attached to

---

development/generate_api_coverage.rb
docs/api_coverage.md
lib/puppeteer/element_handle.rb
spec/integration/element_handle_spec.rb

porting: https://github.com/puppeteer/puppeteer/pull/8329

feat: add waitForXPath to ElementHandle

---

lib/puppeteer/browser.rb
lib/puppeteer/launcher/browser_options.rb
lib/puppeteer/launcher/chrome.rb
lib/puppeteer/launcher/firefox.rb
lib/puppeteer/target.rb

Porting https://github.com/puppeteer/puppeteer/pull/8336, https://github.com/puppeteer/puppeteer/pull/7192

feat: allow handling other targets as pages internally

---

lib/puppeteer/frame.rb
lib/puppeteer/frame_manager.rb
lib/puppeteer/lifecycle_watcher.rb
spec/assets/frames/lazy-frame.html
spec/assets/lazy-oopif-frame.html
spec/integration/frame_spec.rb
spec/integration/oopif_spec.rb

Porting https://github.com/puppeteer/puppeteer/pull/8348

fix: only check loading iframe in lifecycling

---

lib/puppeteer/element_handle.rb
spec/assets/input/select.html
spec/integration/page_spec.rb

Porting https://github.com/puppeteer/puppeteer/pull/8489

fix: parse empty options in <select>

---

lib/puppeteer/element_handle.rb
lib/puppeteer/page.rb
lib/puppeteer/page/screenshot_options.rb
spec/integration/screenshot_spec.rb

Porting https://github.com/puppeteer/puppeteer/pull/8496 and https://github.com/puppeteer/puppeteer/pull/7063

feat: add fromSurface option to page.screenshot

---

lib/puppeteer/element_handle.rb
lib/puppeteer/remote_object.rb
spec/integration/click_spec.rb

Now scrollIntoViewIfNeeded just uses CDP command.
https://github.com/puppeteer/puppeteer/pull/8631

page: fix page.scrollIntoViewIfNeeded method

---

lib/puppeteer/element_handle.rb
spec/integration/launcher_spec.rb

https://github.com/puppeteer/puppeteer/pull/8680
puppeteer-ruby didn't have such bug.

add test for taking a screenshot with null viewport should be possible

---

lib/puppeteer/frame_manager.rb
lib/puppeteer/page.rb

Porting https://github.com/puppeteer/puppeteer/pull/8688

fix: address flakiness in frame handling

---

lib/puppeteer/chrome_target_manager.rb

Porting https://github.com/puppeteer/puppeteer/pull/8748 and https://github.com/puppeteer/puppeteer/pull/8742

fix: resolve target manager init if no existing targets detected

---

lib/puppeteer/browser.rb
lib/puppeteer/chrome_target_manager.rb
lib/puppeteer/connection.rb
lib/puppeteer/target.rb
spec/integration/cdp_session_spec.rb

Porting https://github.com/puppeteer/puppeteer/pull/8788

fix: custom sessions should not emit targetcreated events

---

lib/puppeteer/dom_world.rb
lib/puppeteer/element_handle.rb
lib/puppeteer/frame.rb
lib/puppeteer/query_handler_manager.rb
spec/integration/query_handler_spec.rb

Porting https://github.com/puppeteer/puppeteer/pull/8730

fix: use an xpath query handler

---

lib/puppeteer/lifecycle_watcher.rb

Porting https://github.com/puppeteer/puppeteer/pull/8826

fix: allow multiple navigations to happen in LifecycleWatcher

---

lib/puppeteer/web_socket.rb

I had max open file problems on Mac, but I suppose the problem is on other platforms too.
I'm not familiar with the TCPSocket implementation but it looks like the socket is not being released if it's not explicitly closed, I read that it will be closed when it'll be read from or written to (and catch EOF or something like that), but it never seems to happen and the socket stays in a CLOSED state forever.
The way to reproduce was pretty much (in Rails console):
```
browser = Puppeteer.launch
browser.close
```
Then leave the Rails console open and run "lsof -n" on the PID of the Rails console and there will be a CLOSED TCP socket open like this:
```
ruby    26090 user   17u   IPv4 0xc6ba21f876ff5cbf      0t0                 TCP 127.0.0.1:60104->127.0.0.1:60103 (CLOSED)
```
If you start more …

Close the TCP socket explicitly

---

lib/puppeteer/lifecycle_watcher.rb

refs #263
```
WARN -- : Future can be resolved only once. It's [true, nil, nil], trying to set [true, nil, nil]. (Concurrent::MultipleAssignmentError)
/Users/yusuke-iwaki/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promises.rb:1246:in `rejected_resolution'
/Users/yusuke-iwaki/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promises.rb:692:in `resolve_with'
/Users/yusuke-iwaki/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promises.rb:1365:in `fulfill'
/Users/yusuke-iwaki/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/puppeteer-ruby-0.44.1/lib/puppeteer/lifecycle_watcher.rb:103:in `handle_request' …
```

Accept multiple resolve for wait_for_response.

---

.circleci/config.yml
CHANGELOG.md
lib/puppeteer/element_handle.rb
lib/puppeteer/execution_context.rb
lib/puppeteer/firefox_target_manager.rb
lib/puppeteer/frame.rb
lib/puppeteer/page.rb
lib/puppeteer/page/screenshot_options.rb
spec/integration/cookies_spec.rb
spec/integration/frame_spec.rb
spec/integration/input_spec.rb

Thanks to https://github.com/YusukeIwaki/puppeteer-ruby/pull/276, Firefox is now available.
Some codes are already broken. Fix them to work with Firefox.

Fix codes compatible with Firefox

---

lib/puppeteer/browser_fetcher.rb
lib/puppeteer/puppeteer.rb

puppeteer-ruby assumes the browser is prepared. BrowserFetcher is useless and remove it.

Remove BrowserFetcher

---

docs/api_coverage.md
lib/puppeteer/puppeteer.rb
spec/integration/element_handle_spec.rb

```ruby
Puppeteer.register_custom_query_handler(
name: 'getByClass',
query_one: '(element, selector) => document.querySelector(`.${selector}`)',
query_all: '(element, selector) => document.querySelectorAll(`.${selector}`)',
)
```
```ruby
Puppeteer.with_custom_query_handler(
name: 'getByClass',
query_one: '(element, selector) => document.querySelector(`.${selector}`)',
query_all: '(element, selector) => document.querySelectorAll(`.${selector}`)',
) do
button = page.query_selector('getByClass/btn')
...
end # the handler is unregistered automatically
```

Enable to register custom query handlers

---

lib/puppeteer/keyboard.rb
spec/integration/keyboard_spec.rb

Porting https://github.com/puppeteer/puppeteer/pull/9357

feat: keydown supports commands

---

lib/puppeteer/frame_manager.rb

Partially porting https://github.com/puppeteer/puppeteer/pull/9375

fix oopif flakiness

---

lib/puppeteer/page.rb
lib/puppeteer/page/screenshot_options.rb
spec/integration/screenshot_spec.rb

resolves #298 
```ruby
Puppeteer.launch do |browser|
page = browser.new_page
page.viewport = Puppeteer::Viewport.new(width: 1280, height: 800)
page.goto('https://github.com/YusukeIwaki')
page.screenshot(path: 'YusukeIwaki.png', full_page: false)
end
```
outputs the image below

Explicitly set captureBeyondViewport=false unless fullPage or clip is set

---

lib/puppeteer/browser_runner.rb

On WSLv1 when you set the "executable_path" to a windows browser the websocket url has a carriage return in it and it breaks the code.
`/usr/lib/ruby/3.0.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "ws://127.0.0.1:59359/devtools/browser/7be24a1d-1c2e-4839-a3a9-2516e01e1d20\\r" (URI::InvalidURIError)
from /usr/lib/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
from /usr/lib/ruby/3.0.0/uri/common.rb:171:in `parse'
from /var/lib/gems/3.0.0/gems/puppeteer-ruby-0.45.3/lib/puppeteer/web_socket.rb:24:in `initialize'
from /var/lib/gems/3.0.0/gems/puppeteer-ruby-0.45.3/lib/puppeteer/web_socket.rb:60:in `new'
from /var/lib/gems/3.0.0/gems/puppeteer-ruby-0.45.3/lib/puppeteer/web_socket.rb:60:in `initialize'
from /var/lib/gems/3.0.0/gems/puppeteer-ruby-0.45.3/lib/puppeteer/web_socket_ …

Fixed websocket URL to work with windows google-chrome browser on WSL v1
